db:
  mongoUrl: 'mongodb://jarvis:datamantra890@127.0.0.1/crystal?retryWrites=true&w=majority'
  dbname: 'crystal'
  withUserNameCollection: 'user_with_uname'
  withoutUserNameCollection: 'user_without_uname'

